import type { WorkflowGraph } from './workflow'

export type AgentVersion = {
  _id?: string
  userId: string
  agentId: string
  /** Incrementing version (1,2,3...) or semantic string */
  version: number | string

  /** Prompt/workflow snapshot */
  prompt?: string
  workflow?: WorkflowGraph

  llmProvider?: string

  createdAt: Date
  /** Optional notes (e.g., generated by prompt regeneration) */
  notes?: string
}

